#! /bin/bash


sudo apt-get install git
echo "Intstalling PEDA - GDB  next"
git clone https://github.com/longld/peda.git ~/peda
echo "source ~/peda/peda.py" >> ~/.gdbinit
echo "DONE! debug your program with gdb and enjoy"
