#! /bin/bash

sudo apt-get update
sudo apt-get install gdb
echo "Intstalling PEDA - GDB  next"
git clone https://github.com/longld/peda.git ~/peda
echo "source ~/peda/peda.py" >> ~/.gdbinit
echo "DONE! debug your program with gdb and enjoy"
